# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sdr_worker_pb2 as proto_dot_sdr__worker__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/sdr_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SDRWorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetHealth',
                request_serializer=proto_dot_sdr__worker__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ValidateEarfcns = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/ValidateEarfcns',
                request_serializer=proto_dot_sdr__worker__pb2.EarfcnList.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ValidationResult.FromString,
                _registered_method=True)
        self.StartScan = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/StartScan',
                request_serializer=proto_dot_sdr__worker__pb2.ScanRequest.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetScanStatus',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ScanStatusResponse.FromString,
                _registered_method=True)
        self.GetScanResults = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetScanResults',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ScanResultsResponse.FromString,
                _registered_method=True)
        self.GetCellInfo = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetCellInfo',
                request_serializer=proto_dot_sdr__worker__pb2.CellQuery.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.CellInfoResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetNeighbors',
                request_serializer=proto_dot_sdr__worker__pb2.CellQuery.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.NeighborResponse.FromString,
                _registered_method=True)
        self.GetNeighborMap = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetNeighborMap',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.NeighborMapResponse.FromString,
                _registered_method=True)
        self.GetUnscannedEarfcns = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetUnscannedEarfcns',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.EarfcnList.FromString,
                _registered_method=True)
        self.StopScan = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/StopScan',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.StopResponse.FromString,
                _registered_method=True)
        self.StartGsmScan = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/StartGsmScan',
                request_serializer=proto_dot_sdr__worker__pb2.GsmScanRequest.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.StartGsmBandScan = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/StartGsmBandScan',
                request_serializer=proto_dot_sdr__worker__pb2.GsmBandScanRequest.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.GetGsmScanResults = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetGsmScanResults',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.GsmScanResultsResponse.FromString,
                _registered_method=True)
        self.GetGsmNeighbors = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetGsmNeighbors',
                request_serializer=proto_dot_sdr__worker__pb2.GsmCellQuery.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.GsmNeighborResponse.FromString,
                _registered_method=True)
        self.GetGsmInterRatNeighbors = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/GetGsmInterRatNeighbors',
                request_serializer=proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.GsmInterRatResponse.FromString,
                _registered_method=True)
        self.ValidateArfcns = channel.unary_unary(
                '/sdr_worker.SDRWorkerService/ValidateArfcns',
                request_serializer=proto_dot_sdr__worker__pb2.ArfcnList.SerializeToString,
                response_deserializer=proto_dot_sdr__worker__pb2.ArfcnValidationResult.FromString,
                _registered_method=True)


class SDRWorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateEarfcns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCellInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighborMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnscannedEarfcns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGsmScan(self, request, context):
        """--- GSM Service Extensions ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGsmBandScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGsmScanResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGsmNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGsmInterRatNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateArfcns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SDRWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=proto_dot_sdr__worker__pb2.Empty.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.HealthResponse.SerializeToString,
            ),
            'ValidateEarfcns': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateEarfcns,
                    request_deserializer=proto_dot_sdr__worker__pb2.EarfcnList.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ValidationResult.SerializeToString,
            ),
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanRequest.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ScanResponse.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ScanStatusResponse.SerializeToString,
            ),
            'GetScanResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanResults,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ScanResultsResponse.SerializeToString,
            ),
            'GetCellInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCellInfo,
                    request_deserializer=proto_dot_sdr__worker__pb2.CellQuery.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.CellInfoResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=proto_dot_sdr__worker__pb2.CellQuery.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.NeighborResponse.SerializeToString,
            ),
            'GetNeighborMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighborMap,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.NeighborMapResponse.SerializeToString,
            ),
            'GetUnscannedEarfcns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnscannedEarfcns,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.EarfcnList.SerializeToString,
            ),
            'StopScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScan,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.StopResponse.SerializeToString,
            ),
            'StartGsmScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGsmScan,
                    request_deserializer=proto_dot_sdr__worker__pb2.GsmScanRequest.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ScanResponse.SerializeToString,
            ),
            'StartGsmBandScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGsmBandScan,
                    request_deserializer=proto_dot_sdr__worker__pb2.GsmBandScanRequest.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ScanResponse.SerializeToString,
            ),
            'GetGsmScanResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGsmScanResults,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.GsmScanResultsResponse.SerializeToString,
            ),
            'GetGsmNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGsmNeighbors,
                    request_deserializer=proto_dot_sdr__worker__pb2.GsmCellQuery.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.GsmNeighborResponse.SerializeToString,
            ),
            'GetGsmInterRatNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGsmInterRatNeighbors,
                    request_deserializer=proto_dot_sdr__worker__pb2.ScanId.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.GsmInterRatResponse.SerializeToString,
            ),
            'ValidateArfcns': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateArfcns,
                    request_deserializer=proto_dot_sdr__worker__pb2.ArfcnList.FromString,
                    response_serializer=proto_dot_sdr__worker__pb2.ArfcnValidationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sdr_worker.SDRWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sdr_worker.SDRWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SDRWorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetHealth',
            proto_dot_sdr__worker__pb2.Empty.SerializeToString,
            proto_dot_sdr__worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateEarfcns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/ValidateEarfcns',
            proto_dot_sdr__worker__pb2.EarfcnList.SerializeToString,
            proto_dot_sdr__worker__pb2.ValidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/StartScan',
            proto_dot_sdr__worker__pb2.ScanRequest.SerializeToString,
            proto_dot_sdr__worker__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetScanStatus',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.ScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetScanResults',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.ScanResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCellInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetCellInfo',
            proto_dot_sdr__worker__pb2.CellQuery.SerializeToString,
            proto_dot_sdr__worker__pb2.CellInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetNeighbors',
            proto_dot_sdr__worker__pb2.CellQuery.SerializeToString,
            proto_dot_sdr__worker__pb2.NeighborResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighborMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetNeighborMap',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.NeighborMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnscannedEarfcns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetUnscannedEarfcns',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.EarfcnList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/StopScan',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGsmScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/StartGsmScan',
            proto_dot_sdr__worker__pb2.GsmScanRequest.SerializeToString,
            proto_dot_sdr__worker__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartGsmBandScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/StartGsmBandScan',
            proto_dot_sdr__worker__pb2.GsmBandScanRequest.SerializeToString,
            proto_dot_sdr__worker__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGsmScanResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetGsmScanResults',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.GsmScanResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGsmNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetGsmNeighbors',
            proto_dot_sdr__worker__pb2.GsmCellQuery.SerializeToString,
            proto_dot_sdr__worker__pb2.GsmNeighborResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGsmInterRatNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/GetGsmInterRatNeighbors',
            proto_dot_sdr__worker__pb2.ScanId.SerializeToString,
            proto_dot_sdr__worker__pb2.GsmInterRatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateArfcns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sdr_worker.SDRWorkerService/ValidateArfcns',
            proto_dot_sdr__worker__pb2.ArfcnList.SerializeToString,
            proto_dot_sdr__worker__pb2.ArfcnValidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
